# Generated by Django 4.2.4 on 2023-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('color', models.CharField(choices=[('#CC2936', 'Vermelho'), ('#F4743B', 'Laranja'), ('#f4a261', 'Laranja claro'), ('#e9c46a', 'Amarelo'), ('#E8FCCF', 'Verde claro'), ('#2a9d8f', 'Verde'), ('#264653', 'Verde escuro'), ('#3483FA', 'Azul'), ('#2A2D34', 'cinza escuro'), ('#141414', 'Preto'), ('#FFF9F5', 'Branco')], default='', max_length=100)),
            ],
        ),
    ]
