# Generated by Django 4.2.4 on 2023-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('#CC2936', '🔴 Vermelho'), ('#F4743B', '🟠 Laranja'), ('#e9c46a', '🟡 Amarelo'), ('#2a9d8f', '🟢 Verde'), ('#3483FA', '🔵 Azul'), ('#9448BC', '🟣 Roxo'), ('#141414', '⚫ Preto'), ('#FFF9F5', '⚪ Branco')], default='', max_length=100),
        ),
    ]
