# Generated by Django 4.2.4 on 2023-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0002_rename_name_subject_description_alter_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('red', '🔴 Vermelho'), ('orange', '🟠 Laranja'), ('yellow', '🟡 Amarelo'), ('green', '🟢 Verde'), ('blue', '🔵 Azul'), ('purple', '🟣 Roxo'), ('black', '⚫ Preto'), ('white', '⚪ Branco')], default='', max_length=100),
        ),
    ]
