# Generated by Django 4.2.4 on 2023-09-03 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0005_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='revisions_cycles',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
