# Generated by Django 4.2.4 on 2023-09-03 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0006_alter_study_revisions_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
