# Generated by Django 4.2.4 on 2023-09-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0010_remove_study_is_done_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_revision', to='revise_minder.study'),
        ),
    ]
