# Generated by Django 4.2.4 on 2023-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise_minder', '0011_alter_revision_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='date_plus_1_day',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='date_plus_1_month',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='date_plus_1_week',
        ),
        migrations.AlterField(
            model_name='revision',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
